FROM node:18 AS build
WORKDIR /src
COPY BOA-Frontend/app-ventas-detalle/package*.json ./
RUN npm install
COPY BOA-Frontend/app-ventas-detalle/ ./
RUN sed -i "s|http://localhost:6005|http://localhost:7005|g" src/environments/environment.development.ts
RUN npx ng build --configuration development

FROM nginx:alpine AS runtime
COPY --from=build /src/dist/app-master-detail/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
