FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY BOA-Backend/MSVenta/MSVenta.Venta/*.csproj ./MSVenta.Venta/
RUN dotnet restore ./MSVenta.Venta/BOA.Operaciones.csproj
COPY BOA-Backend/MSVenta/MSVenta.Venta/ ./MSVenta.Venta/
WORKDIR /src/MSVenta.Venta
RUN dotnet publish BOA.Operaciones.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BOA.Operaciones.dll"]
